FROM python:3.9.5-slim

# RUN apt update && \
#     apt install -y bash \
#                    build-essential \
#                    git \
#                    curl \
#                    ca-certificates \
#                    rm -rf /var/lib/apt/lists
                #    python3.9 \
                #    python3-pip && \
    

RUN python3 -m pip install --no-cache-dir --upgrade pip && \
    python3 -m pip install --no-cache-dir --ignore-installed \
    tensorflow-cpu \
    torch \
    numpy \
    sklearn \
    future \
    thulac \
    tqdm \
    transformers

ENV GPT2_ROOT /app
RUN mkdir $GPT2_ROOT
WORKDIR $GPT2_ROOT

COPY . .

ENTRYPOINT [ "bash", "entrypoint.sh" ]