FROM python:3.9.5-slim

RUN python3 -m pip install --no-cache-dir --upgrade pip && \
    python3 -m pip install --no-cache-dir --ignore-installed \
    tensorflow-cpu \
    torch \
    numpy \
    sklearn \
    future \
    thulac \
    tqdm \
    transformers==2.1.1

ENV GPT2_ROOT /app
RUN mkdir $GPT2_ROOT
WORKDIR $GPT2_ROOT

COPY . .

ENTRYPOINT [ "bash", "entrypoint.sh"]