FROM ubuntu:18.04
LABEL maintainer="Hugging Face"
LABEL repository="transformers"

RUN apt update && \
    apt install -y bash \
                   build-essential \
                   git \
                   curl \
                   ca-certificates \
                   python3 \
                   python3-pip && \
    rm -rf /var/lib/apt/lists

RUN python3 -m pip install --no-cache-dir --upgrade pip && \
    python3 -m pip install --no-cache-dir --ignore-installed \
    tensorflow-cpu \
    torch \
    numpy \
    sklearn \
    future \
    thulac \
    tqdm \
    transformers

ENV GPT2_ROOT /app
RUN mkdir $GPT2_ROOT
WORKDIR $GPT2_ROOT

COPY . .

ENTRYPOINT [ "bash", "entrypoint.sh" ]
# CMD ["generate.sh"]
# RUN python3 generate.py --prefix='中國，人民，幸福，第一' --length=50 --nsamples=5 --modal_path='model/model_wiki5_epoch1'
